trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - '*'

variables:
  BuildVersion: '$(Build.BuildNumber)'
  FeedName: ''            
  FeedUrl: ''             
  ModuleSearchPattern: '*.psd1'
  PesterPath: ''          

pool:
  vmImage: 'windows-latest'

stages:
  - stage: CI
    displayName: Build and Test
    jobs:
      - job: build_test
        displayName: Build and Test Modules
        steps:
          - checkout: self

          - task: PowerShell@2
            displayName: Discover + Build + Test
            env:
              SYSTEM_ACCESSTOKEN: $(System.AccessToken)
            inputs:
              targetType: filePath
              filePath: build/ci-discover-and-build.ps1
              arguments: >-
                -RepoRoot "$(Build.SourcesDirectory)"
                -ModuleSearchPattern "$(ModuleSearchPattern)"
                -RunTests
                -Version "$(BuildVersion)"
                -PesterPath "$(PesterPath)"
              pwsh: true

  - stage: Publish
    displayName: Publish Modules
    dependsOn: CI
    condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/main'), startsWith(variables['Build.SourceBranch'], 'refs/heads/release/')))
    jobs:
      - job: publish
        displayName: Publish to Azure Artifacts
        steps:
          - checkout: self

          - task: PowerShell@2
            displayName: Discover + Build + Publish
            env:
              SYSTEM_ACCESSTOKEN: $(System.AccessToken)
            inputs:
              targetType: filePath
              filePath: build/ci-discover-and-build.ps1
              arguments: >-
                -RepoRoot "$(Build.SourcesDirectory)"
                -ModuleSearchPattern "$(ModuleSearchPattern)"
                -Version "$(BuildVersion)"
                -Publish
                -FeedName "$(FeedName)"
                -FeedUrl "$(FeedUrl)"
              pwsh: true
